adding new liquibase
wawandco/oxplugins pull request #9
Opened 2021-01-14 15:17 UTC by YanDeLeon

2021-01-14 15:22 UTC, paganotoni requested changes

2021-01-14 15:22 UTC, paganotoni commented on tools/liquibase/generator.go
> +	fullName := fecha + "-" + underscoreName + ".xml"
@YanDeLeon this one should be done by an inflection library, see https://github.com/gobuffalo/flect/blob/master/underscore.go#L12

2021-01-14 21:48 UTC, dannov91 commented
@paganotoni @YanDeLeon -- I love the shape it's taking!

2021-01-14 22:05 UTC, paganotoni requested changes

2021-01-14 22:05 UTC, paganotoni commented on plugins.go
> +	&liquibase.Generator{},
@YanDeLeon this one will be optional so no need to add it to the list of plugins.

2021-01-14 22:13 UTC, paganotoni requested changes

2021-01-14 22:13 UTC, paganotoni commented on tools/liquibase/generator_test.go
> +		if err != nil {
@YanDeLeon we need to check that the file gets generated and also check its content.

2021-01-15 18:15 UTC, paganotoni approved these changes
Well done @YanDeLeon

2021-01-15 18:15 UTC, merged